apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 50
  selector:
    matchLabels:
      anisa: kubernetes
  template:
    metadata:
      labels:
        anisa: kubernetes
    spec:
     containers:
      - name: apache-container
        image: nginx

